# Generated by Django 3.0.6 on 2020-05-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('jobtitle', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('jobtype', models.CharField(max_length=20)),
                ('paymentmethod', models.CharField(max_length=20)),
                ('jobdescription', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
    ]
