# Generated by Django 3.0.6 on 2020-06-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='createdby',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='offerby',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='privacy',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='tagdev',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='jobdescription',
            field=models.CharField(max_length=200),
        ),
    ]
