# Generated by Django 3.0.6 on 2020-06-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200605_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
