# Generated by Django 3.0.6 on 2020-06-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_offers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='createdby',
        ),
        migrations.AddField(
            model_name='projects',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
