# Generated by Django 3.0.6 on 2020-06-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200621_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='createdby',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
