# Generated by Django 3.0.6 on 2020-06-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projects_createdby'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='projecttitle',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
