# Generated by Django 3.0.6 on 2020-06-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_offers_projecttitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='reccomends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developername', models.CharField(max_length=100, null=True)),
                ('projectid', models.CharField(max_length=100, null=True)),
                ('projecttitle', models.CharField(max_length=100, null=True)),
                ('reccomendedby', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'reccomends',
            },
        ),
        migrations.RemoveField(
            model_name='offers',
            name='projecttitle',
        ),
    ]
