# Generated by Django 3.0.6 on 2020-06-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_reccomends_projectjobtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reccomends',
            name='projectjobtitle',
        ),
        migrations.AddField(
            model_name='offers',
            name='projectjobtitle',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
