# Generated by Django 3.0.6 on 2020-06-22 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20200622_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offers',
            old_name='projectjobtitle',
            new_name='projecttitle',
        ),
    ]
