# Generated by Django 3.0.6 on 2020-06-22 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20200622_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='projecttitle',
        ),
    ]
