# Generated by Django 3.0.6 on 2020-06-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_offers_projecttitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='isAccepted',
            field=models.BooleanField(default=False),
        ),
    ]
