# Generated by Django 3.0.6 on 2020-06-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_offers_isaccepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='isCompletedbyDeveloper',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offers',
            name='isCopletedbyClient',
            field=models.BooleanField(default=False),
        ),
    ]
