# Generated by Django 3.0.6 on 2020-06-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20200623_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='isCompletedbyDeveloper',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='isCopletedbyClient',
        ),
        migrations.AddField(
            model_name='projects',
            name='isCompletedbyDeveloper',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projects',
            name='isCopletedbyClient',
            field=models.BooleanField(default=False),
        ),
    ]
