# Generated by Django 3.0.6 on 2020-06-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20200623_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='developercomments',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
