# Generated by Django 3.0.6 on 2020-06-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_projects_developercomments'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentby', models.CharField(max_length=100)),
                ('projectid', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
