# Generated by Django 3.0.7 on 2020-06-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_projects_developercomments'),
    ]

    operations = [
        migrations.CreateModel(
            name='customerinfo',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('location', models.CharField(default='not available', max_length=22)),
                ('disc', models.CharField(default='not available', max_length=150)),
                ('linkedin', models.CharField(default='not available', max_length=50)),
                ('profile_pic', models.ImageField(upload_to='static/images/')),
            ],
            options={
                'db_table': 'customerinfo',
            },
        ),
        migrations.CreateModel(
            name='developerinfo',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('location', models.CharField(default='not available', max_length=22)),
                ('language', models.CharField(default='not available', max_length=22)),
                ('github', models.CharField(default='not available', max_length=50)),
                ('cv', models.CharField(default='not available', max_length=50)),
                ('profile_pic', models.ImageField(upload_to='static/images/')),
            ],
            options={
                'db_table': 'developerinfo',
            },
        ),
    ]
