# Generated by Django 3.0.7 on 2020-06-28 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_comments'),
        ('projects', '0018_customerinfo_developerinfo'),
    ]

    operations = [
    ]
