# Generated by Django 3.0.7 on 2020-06-28 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_merge_20200628_1803'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comments',
            table=None,
        ),
        migrations.AlterModelTable(
            name='customerinfo',
            table=None,
        ),
        migrations.AlterModelTable(
            name='offers',
            table=None,
        ),
        migrations.AlterModelTable(
            name='projects',
            table=None,
        ),
    ]
