# Generated by Django 3.0.7 on 2020-06-28 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20200628_1814'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comments',
            table='comments',
        ),
        migrations.AlterModelTable(
            name='customerinfo',
            table='customerinfo',
        ),
        migrations.AlterModelTable(
            name='offers',
            table='offers',
        ),
    ]
