# Generated by Django 3.0.7 on 2020-06-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_developerinfo_raing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developerinfo',
            name='raing',
        ),
        migrations.AddField(
            model_name='developerinfo',
            name='rating',
            field=models.CharField(default='0', max_length=4),
        ),
    ]
