# Generated by Django 3.0.5 on 2020-05-10 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Users',
        ),
    ]
