# Generated by Django 3.0.5 on 2020-05-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0002_auto_20200510_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default=1234, max_length=30),
            preserve_default=False,
        ),
    ]
