# Generated by Django 3.0.5 on 2020-05-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0003_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default='Elias', max_length=30),
            preserve_default=False,
        ),
    ]
