# Generated by Django 3.0.5 on 2020-05-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my.auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appusers',
            name='idiotita',
            field=models.CharField(max_length=20),
        ),
    ]
