# Generated by Django 3.0.5 on 2020-05-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my.auth', '0002_auto_20200512_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appusers',
            name='id',
        ),
        migrations.AlterField(
            model_name='appusers',
            name='username',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
