# Generated by Django 3.0.5 on 2020-05-12 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my.auth', '0003_auto_20200512_1646'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appusers',
            table='appusers',
        ),
    ]
