# Generated by Django 3.0.5 on 2020-06-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my.auth', '0004_auto_20200512_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='appusers',
            name='birthday',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appusers',
            name='fullname',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appusers',
            name='location',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
