# Generated by Django 3.0.7 on 2020-06-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my.auth', '0005_auto_20200603_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appusers',
            name='password',
            field=models.CharField(max_length=300),
        ),
    ]
