# Generated by Django 3.0.7 on 2020-06-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my.auth', '0006_auto_20200628_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='appusers',
            name='info1',
            field=models.CharField(default=7, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appusers',
            name='info2',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appusers',
            name='info3',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appusers',
            name='location2',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appusers',
            name='profile_pic',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
