# Generated by Django 3.0.7 on 2020-06-28 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my.auth', '0007_auto_20200628_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appusers',
            name='info1',
        ),
        migrations.RemoveField(
            model_name='appusers',
            name='info2',
        ),
        migrations.RemoveField(
            model_name='appusers',
            name='info3',
        ),
        migrations.RemoveField(
            model_name='appusers',
            name='location2',
        ),
        migrations.RemoveField(
            model_name='appusers',
            name='profile_pic',
        ),
    ]
