# Generated by Django 3.0.7 on 2020-06-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my.auth', '0008_auto_20200628_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='appusers',
            name='rating',
            field=models.CharField(default='0', max_length=4),
        ),
    ]
